### ISSUE TITLE
Disabling Intel RST

### ISSUE THREAD

**Issue by akastoras** [GGkas/install_fest#1]
Όταν πήγα να κάνω εγκατάσταση σε ενα λάπτοπ (εχω ξεχάσει τελειως μοντέλο κλπ) ο installer μου ζητησε να απενεργοποιήσω το Intel RST. Μετά απο πολύ ψάξιμο στο bios δεν βρέθηκε λύση. Αν το ψάξεις και βρεις κάτι καλώς.

**Comment by GGkas** [comment]
Επειδή το έψαξα και εγώ, ακόμα και αν δεν υπάρχει στο BIOS σαν επιλογή, κατά 99% οι δίσκοι είναι σε RAID setup, οπότε πρέπει να γίνει switch από RAID σε AHCI. Θα προσθέσω τα σχετικά βήματα στο **Appendix** για το πώς να γίνει.
